server {
    listen 443;
    server_name ericsebb.qzz.io;

    root /usr/share/nginx/html;
    index index.html;

    location = /landing {
        return 301 /landing/;
    }

    location /landing/ {
        rewrite ^/landing/(.*)$ /$1 break;
        try_files $uri $uri/ =404;
        error_page 404 /landing/404.html;
    }

    location / {
        try_files $uri $uri/ =404;
        error_page 404 /404.html;
    }
}
